#!/usr/bin/env bash
# Configures load balancer

sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install -y haproxy=2.0.*
sudo sed -i "$ a frontend load_balancer\n    bind *:80\n    mode http\n    default_backend web_servers\nbackend web_servers\n    balance roundrobin\n    server 86064-web-02 18.234.105.106:80 check\n    server 86064-web-01 54.89.194.152:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
