#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while x=":" read -r FILE
do
echo "$FILE" | cut -d":" -f1,3,6
done </etc/passwd
