#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=':' read username password uid gid info home shell; do
  echo "The user $username is part of the $group_id gang,"\
  "lives in $home_directory and rides $command/$shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $user $id $info"
done < "/etc/passwd"
